#!/bin/bash

set -e
set -o pipefail

curl -s "https://go.dev/dl/?mode=json" | \
  jq -r '.[0].files[] | select(.os=="linux" and (.arch=="amd64" or .arch=="arm64")) | "\(.sha256)  tmp/\(.arch).tar.gz"' | \
  tee SHA256SUM
